##
# Development Container
##
services:
  # Development Container
  dev-tiny-node-api:
    build:
      context: '../'
      dockerfile: './.devcontainer/Dockerfile'
    container_name: 'dev-tiny-node-api'
    restart: 'unless-stopped'
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '../:/workspace'
      - 'node_modules:/workspace/node_modules'
    env_file: '.env'
    environment:
      TZ: 'Europe/Berlin'

##
# Volumes
##
volumes:
  # node_modules
  node_modules:
